name: UPS Validation

on:
  repository_dispatch:
    types: [lava-trigger]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Receive Value
        run: |
          echo "Received XSHIP:"
          echo "${{ github.event.client_payload.xship }}"

      - name: Update Validation File
        run: |
          echo "${{ github.event.client_payload.xship }}" > validation.txt

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add validation.txt
          git commit -m "Auto UPS Update" || exit 0
