name: UPS Validation 2

on:
  repository_dispatch:
    types: [lava-trigger]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create branch
        run: |
          BRANCH=auto-${{ github.run_id }}
          git checkout -b $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Update DIB Path
        env:
          BM_PATH: ${{ github.event.client_payload.path }}
        run: |
          python << 'EOF'
          from pathlib import Path
          import os
          import re
      
          notebook = Path("PT_VMIN_UPSVF_update.dib")
      
          text = notebook.read_text(encoding="utf-8")
      
          full_path = os.environ["BM_PATH"] + r"\flexboms\Release V1.0.0"
      
          text = re.sub(
              r'ups\.SetAllFromFlexBomLavaRelease\(@".*?"\)',
              f'ups.SetAllFromFlexBomLavaRelease(@"{full_path}")',
              text
          )
      
          notebook.write_text(text, encoding="utf-8")
          EOF

      - name: Verify
        run: |
          grep -n "SetAllFromFlexBomLavaRelease" PT_VMIN_UPSVF_update.dib

      # run your dib notebook here

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add PT_VMIN_UPSVF_update.dib
          git commit -m "Update DIB path"

      - name: Push
        run: |
          git push origin $BRANCH
